# Generated by Django 5.0.7 on 2025-08-06 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsexshop', '0004_calificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domiciliario',
            name='Contrasena',
        ),
    ]
